### ISSUE TITLE
Weird window size creep

### ISSUE THREAD

**Issue by jossriLDR** [RegenJacob/egui_logger#1]
I have an egui App with eframe + 4 Panels. The egui logger widget is in the bottom panel:

```rust
impl eframe::App for TemplateApp {
    fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
        egui::TopBottomPanel::top("top_panel").show(ctx, |ui| {
         // ...
        });

        egui::SidePanel::left("side_panel").show(ctx, |ui| {
         // ...
        });

        egui::CentralPanel::default().show(ctx, |ui| {
         // ...
        });

        egui::TopBottomPanel::bottom("bottom_panel").show(ctx, |ui| {
            egui_logger::logger_ui(ui);
        });
     }
}
```

When I start this application I get this weird creep in window size:

[window_creep.webm](https://user-images.githubusercontent.com/86672004/199482310-38e466fb-bdf3-4372-95b2-47b745c7e6e5.webm)

I would expect it to have a fixed size (at least as long as no new messages appear). Any idea how to resolve this?

**Comment by RegenJacob** [comment]
seems like my last commit did this i'll fix it tomorrow

**Comment by RegenJacob** [comment]
it should work now

**Comment by jossriLDR** [comment]
Yes, thank you.
