### ISSUE TITLE
Usage with multi_log

### ISSUE THREAD

**Issue by nikoof** [RegenJacob/egui_logger#13]
I am trying to use egui_logger with [multi_log](https://github.com/davechallis/multi_log) (which seems pretty dead as a project, but anyhow). I think all that should be done to make this possible (and probably to allow integrating with other similar crates) is to make the `EguiLogger` struct public. From what I've observed using [this](https://github.com/nikoof/egui_logger), it seems to work ok. I can open a PR if needed.

**Comment by RegenJacob** [comment]
A PR would be awesome! Could you maybe add an example

**Comment by nikoof** [comment]
Sure! Shouldn't be too complicated, I'll have it done by tomorrow or so.
