### ISSUE TITLE
Upstream Azkellas/egui_logger changes

### ISSUE THREAD

**Issue by Azkellas** [RegenJacob/egui_logger#21]
I recently [forked egui_logger](https://github.com/Azkellas/egui_logger) and extended it to fit my needs.

As I changed many things (and think my needs are different from yours) I'm opening this issue to discuss about what we can upstream in the crate.

Changes made:
- Add a `Category` filter (category = log target, e.g. `my_crate::my_module`)
- Display log time
  - local time (`HH:MM:SS` or `HH:MM:SS.mmm`)
  - time since start (`Xh Ym Zs Mms`)
- Display and highlight log target
- Disable alphabetic sorting of log entries (`sort` feature)
- Display in monospace to align text

Are there any feature you're interested in?

 
[egui_logger.webm](https://github.com/user-attachments/assets/63b51c02-a44e-4fe9-896a-6a2e0d06c053)

**Comment by RegenJacob** [comment]
Very nice work, looks great! 

I will take a look tomorrow but your changes seem very good!
I also was a bit unhappy with alphabetic sort and I doubt that anyone would miss that.

I would be happy to review a PR and probably change a few things myself.

Thank you!

**Comment by Azkellas** [comment]
Great! I made the PR. Code is a bit "raw", feel free to modify it or ask me to do it.

**Comment by izolyomi** [comment]
Thank you for this crate and all the extension efforts, I agree that the changes make the crate much more practical and usable.
Can we expect the PR to be merged for a 0.6 crate release, are there any related recent news?

**Comment by RegenJacob** [comment]
@izolyomi Yes I will try to merge this soon, however I'm currently a bit busy so it might take a while. I'm not really happy about the formatting so I'd have to look a bit further into that before merging.

**Comment by izolyomi** [comment]
A kind reminder: can we expect any upcoming updates?

**Comment by RegenJacob** [comment]
> A kind reminder: can we expect any upcoming updates?

I'm still a bit busy but if I might merge without changes if don't find the time this week

**Comment by RegenJacob** [comment]
Closed by #22
