### ISSUE TITLE
Egui 0.29 support

### ISSUE THREAD

**Issue by izolyomi** [RegenJacob/egui_logger#24]
The ecosystem is moving fast and egui 0.29 was recently released. Would it be possible to update the dependencies of this crate to egui 0.29?
As an even better alternative, probably the best solution would be to support multiple egui versions using crate features, see https://github.com/PingPongun/egui_struct for an example.

**Comment by RegenJacob** [comment]
I'll update it to 0.29 for now. 
 

> support multiple egui versions using crate features 

seems interesting but I don't think egui moves that fast to consider that (at least for now), but I might look into that in the futute
