### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [RegenJacob/egui_logger#25]
Hi Jacob, just found your work, so thanks... a few questions...

1. Did you write this from scratch? Oh, i see that you are using the "log" crate.
2. Is it thread safe?
3. Are you able to write to files?  Simplelog writes very nicely to files but I cannot get it to work to write to a string that I can actually access from egui.

**Comment by RegenJacob** [comment]
Hi there! 

> Did you write this from scratch? Oh, i see that you are using the "log" crate.

egui_logger is an implementation/frontend for the log crate. Many other Rust libraries and programs use log to make logging comfortable.


 > Is it thread safe?

 It should be


> Are you able to write to files? Simplelog writes very nicely to files but I cannot get it to work to write to a string that I can actually access from egui.

Currently you could accomplish this with the [multi_log](https://github.com/RegenJacob/egui_logger/blob/main/examples/multi_log.rs) example and just replacing env_logger with simple_logging. I haven't tested it myself but it should work. And I am thinking of implementing native file safes, but I currently am quite busy and multi_log should cover this use case right now.

**Comment by RegenJacob** [comment]
I'll close this for now. If you have any other questions feel free to ask!
